In [2]:
#Load the data
import pandas as pd
data = pd.read_csv('dataset_Seminar1.txt', sep=' ', header=None)
display(data.head())

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,40.0,60000000.0,22.0,39.0,858.0,63.0,80.0,4000.0,-42.928330,-63.163012,-74.965338,0.415189,7.208644e+06,1.229466e+07,1.084041,0.875490
1,35.0,52500000.0,20.0,33.0,660.0,31.0,40.0,10000.0,-47.815800,-63.298410,-72.847989,0.485311,1.545116e+07,1.275042e+07,1.111263,0.873785
2,16.0,12000000.0,34.0,14.0,476.0,255.0,40.0,4000.0,-46.138494,-60.076333,-70.044800,0.099413,6.743660e+06,2.251690e+06,0.880036,0.849701
3,37.0,18500000.0,35.0,7.0,245.0,31.0,80.0,10000.0,-42.708813,-60.141393,-72.029643,0.493704,1.675025e+07,1.211374e+07,1.126341,0.860103
4,18.0,4500000.0,36.0,35.0,1260.0,127.0,160.0,8000.0,-45.492991,-63.780783,-76.225550,0.011664,4.500000e+06,1.446000e-03,0.276770,0.275687

In [ ]:
#Añadimos labels a la data porque me vuelvo loco. (Perdón por comentarios en varios idiomas voy a ir cambiando según el último idioma que haya leído)
data.columns = ["Num of STAs", "Throughput", "Size(x)", "Size(y)", "Area(xy)", "Contention Window", 
                "Channel Width", "Packet Size", "Max RSSI", "Avg RSSI", "Min RSSI", "Avg Prob of Failure", 
                "Throughput", "Average Delay", ]

In [9]:
# 3. Mostrar estadísticas básicas (Requisito Parte I) [cite: 11]
print("Estadísticas del dataset:")
display(data.describe().loc[['mean', 'std']])

display(data.head())

Estadísticas del dataset:

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
mean,21.446170,2.140292e+07,20.562940,20.479640,421.270350,227.043920,75.106000,7997.580000,-45.911165,-57.577426,-66.467827,0.226676,9.716009e+06,4.688176e+06,0.780560,0.660724
std,11.554365,1.852042e+07,11.545206,11.540626,360.344349,323.350855,53.704279,2825.532513,5.400265,6.108548,8.057528,0.224848,4.958025e+06,7.875887e+06,0.360426,0.256756

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,40.0,60000000.0,22.0,39.0,858.0,63.0,80.0,4000.0,-42.928330,-63.163012,-74.965338,0.415189,7.208644e+06,1.229466e+07,1.084041,0.875490
1,35.0,52500000.0,20.0,33.0,660.0,31.0,40.0,10000.0,-47.815800,-63.298410,-72.847989,0.485311,1.545116e+07,1.275042e+07,1.111263,0.873785
2,16.0,12000000.0,34.0,14.0,476.0,255.0,40.0,4000.0,-46.138494,-60.076333,-70.044800,0.099413,6.743660e+06,2.251690e+06,0.880036,0.849701
3,37.0,18500000.0,35.0,7.0,245.0,31.0,80.0,10000.0,-42.708813,-60.141393,-72.029643,0.493704,1.675025e+07,1.211374e+07,1.126341,0.860103
4,18.0,4500000.0,36.0,35.0,1260.0,127.0,160.0,8000.0,-45.492991,-63.780783,-76.225550,0.011664,4.500000e+06,1.446000e-03,0.276770,0.275687

In [10]:
# 1. Calcular Q1 (25%) y Q3 (75%) para cada columna numérica
Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1

# 2. Definir límites (el factor 1.5 es el estándar de la industria)
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# 3. Filtrar el dataset: solo nos quedamos con filas dentro de los límites
data_clean = data[~((data < limite_inferior) | (data > limite_superior)).any(axis=1)]

print(f"Registros originales: {len(data)}")
print(f"Registros tras limpieza: {len(data_clean)}")
print(f"Outliers eliminados: {len(data) - len(data_clean)}")

Registros originales: 100000
Registros tras limpieza: 79258
Outliers eliminados: 20742